### ISSUE TITLE
Hey Khang, can you pls share your AssetStudio fork that can load .blk files directly pls ? 

### ISSUE THREAD

**Issue by izmare** [khang06/misc#1]
I came across a github repo about datamining Genshin that referenced to your repo. Unfortunately when I click on it I found that it got DCMA takedown. If you still have archive of it I hope you can please share download link to it again, even if temporarily. Thank you in advance! Mong bạn sẽ giúp mk

**Comment by khang06** [comment]
razmoth continued the development of that here: https://github.com/RazTools/Studio
